# Comparação de performance

Nesta aula vamos avaliar a velocidade de processamento para obter um resultado no Python porém, avaliando as diferenças entre **velocidade** e quantidade de **código escrito** para cada caso.

1. **Exemplo 1** vamos trabalhar com um vetor de 10_000_000 de valore e estamos interessados em elevar cada valor ao quadrado. Para conseguir este resultado vamos aplicar:
  - for
  - list comprenhension
  - set comprenhension
  - generators
  - Numpy

2.  **Exemplo 2** vamos trabalhar com vetor de 10_000_000 valores aleatórios entre 0 e 2$\pi$ com média de $\pi$ e desvio padrão de $\pi$. Estamos interessados em calcular:
  - Aplicar a função seno para cada valor;
  - Calcular o valor máximo;
  - Calcular a média;
  - Calular o desvio padrão.
  
  Para conseguir este resultado vamos aplicar:
  - Loop for;
  - Loop for versão 2;
  - list comprenhension (com sum, len, mean e std built-in);
  - generator;
  - numpy;

## Exemplo 1
---

In [16]:
NUMERO_DE_ELEMENTOS = 100_000
vetor = range(1, NUMERO_DE_ELEMENTOS + 1)

### Utilizando `for`

In [2]:
vetor_square_for = []
for valor in vetor:
    vetor_square_for.append(valor**2)
vetor_square_for

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 20449

In [14]:
import timeit
REPEAT = 500 # Quantidade de vezes que será medido o tempo de execução
NUMBER = 10 # Quantidade de vezes que será executado o código
setup_codigo = '''
NUMERO_DE_ELEMENTOS = 100_000
vetor = range(1, NUMERO_DE_ELEMENTOS + 1)
'''
avalidar_codigo = '''
vetor = range(1, NUMERO_DE_ELEMENTOS + 1)
vetor_square_for = []
for valor in vetor:
    vetor_square_for.append(valor**2)'''
tempo_explo1_for= np.array(timeit.repeat(setup=setup_codigo,
                                         stmt=avalidar_codigo,
                                         repeat=REPEAT,
                                         number=NUMBER))/NUMBER
tempo_explo1_for

array([0.03852363, 0.03604391, 0.03863412, 0.03883458, 0.03667568,
       0.03437803, 0.03540947, 0.03474247, 0.03702844, 0.03486625,
       0.03624851, 0.03497194, 0.03524016, 0.03777032, 0.03446558,
       0.0346933 , 0.03439682, 0.0346942 , 0.03477522, 0.03648448,
       0.03468   , 0.0354642 , 0.03453741, 0.03464793, 0.0353198 ,
       0.03485249, 0.03471877, 0.03469157, 0.03542094, 0.03468955,
       0.03508303, 0.03444171, 0.03501206, 0.03487387, 0.03829049,
       0.03466556, 0.03482339, 0.03482674, 0.0369533 , 0.03662477,
       0.03524321, 0.03488527, 0.03526198, 0.03441705, 0.03452817,
       0.03458238, 0.03596954, 0.03597645, 0.03457568, 0.03486143,
       0.03457748, 0.03428921, 0.03440895, 0.03528705, 0.03539557,
       0.0344626 , 0.03438393, 0.03459022, 0.03538223, 0.03480765,
       0.03435612, 0.03525539, 0.03430187, 0.03434834, 0.03450922,
       0.03749725, 0.04345022, 0.03645994, 0.03603857, 0.04173595,
       0.04775989, 0.03479281, 0.03474139, 0.03685434, 0.03431

### Utilizando `list comprenhension`

In [17]:
vetor_square_lc = [valor**2 for valor in vetor]
vetor_square_lc

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 20449

In [18]:
import timeit
REPEAT = 500 # Quantidade de vezes que será medido o tempo de execução
NUMBER = 10 # Quantidade de vezes que será executado o código
setup_codigo = '''
NUMERO_DE_ELEMENTOS = 100_000
vetor = range(1, NUMERO_DE_ELEMENTOS + 1)
'''
avalidar_codigo = '''
vetor_square_lc = [valor**2 for valor in vetor]'''
tempo_explo1_lc= np.array(timeit.repeat(setup=setup_codigo,
                                         stmt=avalidar_codigo,
                                         repeat=REPEAT,
                                         number=NUMBER))/NUMBER
tempo_explo1_lc

array([0.0299905 , 0.0260951 , 0.02658937, 0.02828738, 0.03163879,
       0.02829554, 0.03414739, 0.03368471, 0.03069127, 0.03285105,
       0.03377921, 0.03097004, 0.03187922, 0.03077804, 0.03108602,
       0.03142759, 0.03271469, 0.03107552, 0.03351972, 0.03351513,
       0.03179675, 0.03515884, 0.03399478, 0.03184876, 0.0320519 ,
       0.03108772, 0.03104813, 0.03194461, 0.03231031, 0.03306598,
       0.03198858, 0.03100224, 0.03123876, 0.03135176, 0.03153977,
       0.03144698, 0.03114719, 0.03127533, 0.03096258, 0.03101824,
       0.03187678, 0.03126939, 0.03346724, 0.03621293, 0.03095098,
       0.03125861, 0.03136595, 0.03103556, 0.03092233, 0.03161243,
       0.03101166, 0.03098745, 0.03128513, 0.03117113, 0.03126877,
       0.03106586, 0.03077161, 0.0351198 , 0.03104754, 0.03113191,
       0.03110365, 0.0310417 , 0.03123512, 0.03132262, 0.03121257,
       0.03156014, 0.03175232, 0.03106909, 0.03140656, 0.03090049,
       0.03092922, 0.03147751, 0.03100811, 0.03151212, 0.03103

### Utilizando `set comprenhension`

In [21]:
vetor_square_sc = {valor**2 for valor in vetor}
vetor_square_sc

333338333350000
333338333350000


In [22]:
import timeit
REPEAT = 500 # Quantidade de vezes que será medido o tempo de execução
NUMBER = 10 # Quantidade de vezes que será executado o código
setup_codigo = '''
NUMERO_DE_ELEMENTOS = 100_000
vetor = range(1, NUMERO_DE_ELEMENTOS + 1)
'''
avalidar_codigo = '''
vetor_square_sc = {valor**2 for valor in vetor}'''
tempo_explo1_sc= np.array(timeit.repeat(setup=setup_codigo,
                                         stmt=avalidar_codigo,
                                         repeat=REPEAT,
                                         number=NUMBER))/NUMBER
tempo_explo1_sc

array([0.047704  , 0.04606957, 0.04757425, 0.04350521, 0.043478  ,
       0.04412337, 0.04627959, 0.04362234, 0.04442268, 0.0482433 ,
       0.04969539, 0.05348482, 0.05066171, 0.04894301, 0.05520898,
       0.04784135, 0.04903135, 0.04829397, 0.04988402, 0.05045216,
       0.05399786, 0.05001356, 0.04607463, 0.04825744, 0.04565138,
       0.0465225 , 0.04770334, 0.04635695, 0.04560152, 0.05316706,
       0.04729917, 0.04433965, 0.04458229, 0.04618723, 0.04569871,
       0.0465891 , 0.0443701 , 0.04618788, 0.04570897, 0.04533788,
       0.04480428, 0.04523844, 0.04480413, 0.0460492 , 0.04580046,
       0.04472874, 0.04643991, 0.04705112, 0.0451912 , 0.04399222,
       0.04338433, 0.04494646, 0.0454902 , 0.04754217, 0.04709753,
       0.04468154, 0.04652199, 0.04579335, 0.04374416, 0.04365455,
       0.04441454, 0.04649053, 0.04424034, 0.05045361, 0.0450443 ,
       0.04485135, 0.04540908, 0.0461461 , 0.04441192, 0.04388263,
       0.04784232, 0.04434315, 0.04433976, 0.04458245, 0.04594

### Utilizando  `generators`

In [24]:
vetor_square_gen = (valor**2 for valor in vetor)
list(vetor_square_gen)

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 20449

In [34]:
import timeit
REPEAT = 500 # Quantidade de vezes que será medido o tempo de execução
NUMBER = 10 # Quantidade de vezes que será executado o código
setup_codigo = '''
NUMERO_DE_ELEMENTOS = 100_000
vetor = range(1, NUMERO_DE_ELEMENTOS + 1)
'''
avalidar_codigo = '''
vetor_square_gen = (valor**2 for valor in vetor)'''
tempo_explo1_gen = np.array(timeit.repeat(setup=setup_codigo,
                                         stmt=avalidar_codigo,
                                         repeat=REPEAT,
                                         number=NUMBER))/NUMBER
tempo_explo1_gen

array([1.92380030e-06, 1.18739990e-06, 1.11589979e-06, 1.10670007e-06,
       1.07430023e-06, 1.10080000e-06, 1.08930035e-06, 1.09169996e-06,
       1.07919986e-06, 1.13099959e-06, 1.07840024e-06, 1.04999999e-06,
       1.05820000e-06, 1.06300067e-06, 1.05820000e-06, 1.06920052e-06,
       1.06579973e-06, 1.09879984e-06, 1.08169988e-06, 1.07650048e-06,
       1.07789965e-06, 1.06589941e-06, 1.07480009e-06, 1.07499945e-06,
       1.07330052e-06, 1.07209999e-06, 1.07430023e-06, 1.05760046e-06,
       1.05340005e-06, 1.06759981e-06, 1.06930020e-06, 1.06170046e-06,
       1.09020039e-06, 1.06129955e-06, 1.06430016e-06, 1.07980013e-06,
       1.06759981e-06, 1.07279993e-06, 1.08139939e-06, 1.06520019e-06,
       1.08370004e-06, 1.07360029e-06, 1.05420040e-06, 1.06299995e-06,
       1.06969965e-06, 1.05250001e-06, 1.09089960e-06, 1.06730004e-06,
       1.06559964e-06, 1.07919986e-06, 1.07430023e-06, 1.11979971e-06,
       1.07410015e-06, 1.06209991e-06, 1.06779989e-06, 1.04999999e-06,
      

### Utilizando `Numpy` Opção 1

In [37]:
import numpy as np
vetor_square_np1 = np.square(vetor)

In [39]:
import timeit
REPEAT = 500 # Quantidade de vezes que será medido o tempo de execução
NUMBER = 10 # Quantidade de vezes que será executado o código
setup_codigo = '''
import numpy as np
NUMERO_DE_ELEMENTOS = 100_000
vetor = range(1, NUMERO_DE_ELEMENTOS + 1)
'''
avalidar_codigo = '''
vetor_square_np1 = np.square(vetor)'''
tempo_explo1_np1 = np.array(timeit.repeat(setup=setup_codigo,
                                         stmt=avalidar_codigo,
                                         repeat=REPEAT,
                                         number=NUMBER))/NUMBER
tempo_explo1_np1

array([0.02139032, 0.01942195, 0.01999226, 0.0195505 , 0.02154257,
       0.02603967, 0.02209167, 0.01990776, 0.01998403, 0.01916583,
       0.0194416 , 0.02001478, 0.02015065, 0.01955165, 0.01952355,
       0.01983128, 0.01952674, 0.0199148 , 0.01946495, 0.01941024,
       0.01949098, 0.01948526, 0.01988692, 0.01945107, 0.01932506,
       0.02074571, 0.01991767, 0.02010422, 0.01947829, 0.01926634,
       0.01993287, 0.01999429, 0.02045254, 0.01953161, 0.01997252,
       0.02076193, 0.01969425, 0.02403062, 0.0198652 , 0.01951963,
       0.01918607, 0.01973296, 0.02228109, 0.0194549 , 0.0194926 ,
       0.01987287, 0.02008171, 0.02078302, 0.01976625, 0.0193354 ,
       0.02163219, 0.01963697, 0.02068962, 0.02154171, 0.01954807,
       0.01972369, 0.02217771, 0.02002582, 0.02041083, 0.01909754,
       0.01914699, 0.01974946, 0.02030479, 0.01941341, 0.01950663,
       0.02001829, 0.01953877, 0.02012748, 0.01936229, 0.01923787,
       0.01978159, 0.01964349, 0.02021623, 0.02200726, 0.02032

In [43]:
import numpy as np
vetor_square_np2 = np.array(vetor)**2
vetor_square_np2

array([          1,           4,           9, ...,  9999600004,
        9999800001, 10000000000])

In [44]:
import timeit
REPEAT = 500 # Quantidade de vezes que será medido o tempo de execução
NUMBER = 10 # Quantidade de vezes que será executado o código
setup_codigo = '''
import numpy as np
NUMERO_DE_ELEMENTOS = 100_000
vetor = range(1, NUMERO_DE_ELEMENTOS + 1)
'''
avalidar_codigo = '''
vetor_square_np2 = np.array(vetor)**2'''
tempo_explo1_np2 = np.array(timeit.repeat(setup=setup_codigo,
                                         stmt=avalidar_codigo,
                                         repeat=REPEAT,
                                         number=NUMBER))/NUMBER
tempo_explo1_np2

array([0.02167261, 0.01976237, 0.02037712, 0.02272425, 0.02261819,
       0.02724358, 0.02037382, 0.02043226, 0.02037969, 0.01905444,
       0.02019627, 0.02000683, 0.02295003, 0.02341644, 0.02282502,
       0.02267558, 0.02024486, 0.0214988 , 0.01994085, 0.01988827,
       0.02056954, 0.01959264, 0.02009818, 0.01957123, 0.02009815,
       0.01989419, 0.01982465, 0.02106492, 0.01978685, 0.01949588,
       0.02059721, 0.01940606, 0.02054075, 0.02289592, 0.02295047,
       0.01977717, 0.02039907, 0.0197539 , 0.01901346, 0.01951733,
       0.01972838, 0.01989154, 0.0201291 , 0.0198012 , 0.0195492 ,
       0.0199069 , 0.02005246, 0.01986663, 0.01897519, 0.01996287,
       0.02001458, 0.01997947, 0.0198773 , 0.01976889, 0.02018139,
       0.01956463, 0.02009728, 0.02261169, 0.02055774, 0.01972458,
       0.01948479, 0.01948389, 0.01957946, 0.02163793, 0.01980209,
       0.02210702, 0.02248255, 0.01942855, 0.01948644, 0.01928405,
       0.02005508, 0.01971464, 0.0218075 , 0.02437982, 0.02016

In [45]:
np.sum(tempo_explo1_gen)

10.484660254000481