# Aula 11. NumPy

NumPy é uma das bibliotecas mais poderosas da linguagem Python. Esta biblioteca trabalha com matrizes e arrays multidimensionais. Possui uma grande coleção de funções para realizar operações matemáticas com alta performance (como vimos na aula de comparação performática).

- Esta biblioteca possui seus próprios tipos de dados os quais são do tipo `numpy.ndarray`;
- Trabalhar com matrizes e vetores usando np.ndarrays é mais eficiente que utilizar objetos do tipo lista;
- Numpy é utilizada amplamente para realizar:
    - Computação quântica;
    - Computação estatística; 
    - Processamento de sinal;
    - Processamento de imagem;
    - Visualização 3D;
    - Computação simbólica;
    - Processamento astronômico;
    - BioInoformatica;
    - Inferência Bayesiana;
    - Análise matemática;
    - Simulação e modelagem (Monte Carlo);
    - Análise de multivariável;
    - E infinidades de outras alternativas.
- Recomendo (fortemente) visitar o site de [Numpy](https://numpy.org/) para conhecer mais sobre esta biblioteca.
---
O objetivo de hoje é apresentar os aspectos **mais básicos** desta biblioteca devido a que conta com grande variedades de funções e aplicações. Vamos nos concentrar em:
- List vs Numpy;
- Indexação e fatiamento Numpy;
- Arrays fila e arrays coluna;
- Eliminando elementos, função delete;
- Adicionando elementos insert e append;
- Operações algebraicas com arrays (+, -, *, /, //, %);
- Cannivete NumPy:
 - Array arange;
 - Shape;
 - Size;
 - reshape;
 - Dimension;
 - asarray;
 - Array de zeros;
 - where;
 - Array de 1.
- Carregando dados com Numpy.


## Listas vs Numpy

In [1]:
import numpy as np

In [2]:
l1  = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]
l1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
# Acessando à primeira fila
l1[0]

[1, 2, 3]

In [6]:
# E para acessar à primeira coluna?
l1[:]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
array1  = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Acessando à primeira fila
array1[0,:]

array([1, 2, 3])

In [12]:
# Acessando à primeira coluna
array1[:, -1]

array([3, 6, 9])

## Indexação e fatiamento

Os Arrays se comportam da mesma forma que as listas (até certo ponto), a sua indexação inicia em 0 e vai até o último elemento representado por -1.

In [13]:
array = np.array([0,1,2,3,4,5,6])

In [14]:
print(array) # Imprimindo o array
print(array[:]) # acessando ao todos os elementos
print(array[0]) # acessando ao primer elemento
print(array[1]) # acessando ao segundo elemento
print(array[-1]) # acessando ao ultimo elemeto

[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6]
0
1
6


In [19]:
print(array[1:-1]) # fatiando um array 
print(array[0:3]) # fatiando um array
print(array[0::2]) # fatiando um array com `step`
# Observemos que o último é excluido

[1 2 3 4 5]
[0 1 2]
[0 2 4 6]


Como seria o fatiamento de uma matriz?

$$array =   \left( \begin{matrix} a & b \\ c & d \end{matrix} \right)$$
$$array[:, 0] =   \left( \begin{matrix} a & c  \end{matrix} \right)$$
$$array[0, :] =   \left( \begin{matrix} a & b  \end{matrix} \right)$$
$$array[row, colum])$$

In [ ]:
# Como seria o fatiamento com uma matriz?
print("Array original")
print(array1[:]) # Toda a matriz

In [ ]:
print("Todos os elementos da primeira fila")
print(array1[0, :]) # Todos os elementos da primeira fila
print(array1[0])
print(array1[0][:])

In [ ]:
print("Todos os elementos da última fila")
print(array1[-1, :]) # Todos os elementos da última fila
print(array1[-1][:]) 
print(array1[-1]) 

In [ ]:
print("Todos os elementos da primeira coluna")
print(array1[:, 0]) # Todos os elementos da primeira coluna
print(array1[:][0]) # ?

In [ ]:
print("Todos os elementos da última coluna")
print(array1[:, -1]) # Todos os elementos da última coluna

In [ ]:
print("segundo elemento da segunda coluna")
print(array1[1, 1]) # segundo elemento da segunda coluna

## Array fila e array coluna

Algumas IDEs podem mostrar os array coluna da mesma forma que um array vetor. Porém esses são objetos diferentes. Além disso, algumas operações matriciais precisam do vetor em configurado como uma fila e não como uma coluna.

In [ ]:
array = np.array([1, 2, 3])
array_coluna = np.array([[1], [2], [3]])
array_fila = np.array([[1, 2, 3]])

In [ ]:
print(array)
print(array_coluna)
print(array_fila)

In [ ]:
print("size")
print(array.size)
print(array_coluna.size)
print(array_fila.size)

In [ ]:
print("shape")
print(array.shape)
print(array_coluna.shape)
print(array_fila.shape)

In [ ]:
print("Dimensão")
print(array.ndim)
print(array_coluna.ndim)
print(array_fila.ndim)

## Eliminando elementos, função delete

In [ ]:
print("Arrey Original")
print(array1)
print("-"*15)
print("Eliminando a primeira fila")
print(np.delete(array1, 0, 0)) # Eliminando a primeira fila
print("-"*15)
print("Eliminando a primeira coluna")
print(np.delete(array1, 0, 1)) # Eliminando a primeira coluna

## Adicionando elementos append e insert 

### append

In [ ]:
print("Array original")
print(np.array(np.array([1, 2, 3])))
print("Adicionando todos os elementos no final do array 1D")
np.append(array, [7, 8, 9])  # Adicionando todos os elementos no final do array 1D

In [ ]:
print("Array original")
print(np.array([[1, 2, 3]]) )
print("Adicionando os elementos como uma nova fila")
np.append(array, [[10, 20, 30]], axis=0) # Adicionando os elementos como uma nova fila

In [ ]:
print("Array original")
print(np.array([[1, 2, 3]]))
print("Adicionando os elementos como novas colunas")
np.append(array, [[10, 20, 30]], axis=1) # Adicionando os elementos como novas colunas

### insert

In [ ]:
print("Array original")
print(array1)
print("-"*15)
print("Adicionando uma fila com o mesmo valor")
print(np.insert(array1, 0, 100, 0)) # Adicionando uma fila com o mesmo valor
print("-"*15)
print("Adicionando uma coluna com o mesmo valor")
print(np.insert(array1, 0, 100, 1)) # Adicionando uma coluna com o mesmo valor
print("-"*15)

In [ ]:
print("Array original")
print(array1)
print("-"*15)
print("Adicionando uma fila com o mesmo valor")
print(np.insert(array1, 0, [100, 200, 300], 0)) # Adicionando uma fila com o mesmo valor
print("-"*15)
print("Adicionando uma coluna com o mesmo valor")
print(np.insert(array1, 0,  [100, 200, 300], 1)) # Adicionando uma coluna com o mesmo valor
print("-"*15)

### Modificando um unico elemento

In [ ]:
print("Array original")
array1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print(array1)
print("Array modificado")
array1[1, 1] = 500
print(array1)

## Operações algebraicas
Uma das vantagens dos numpy.ndarray é que as operações algebraicas estão definidas entre esse tipo de dados e dados do tipo numérico como float, int e complex. 

Lembrando que estas operações não estão definidas entre objetos do tipo lista

In [ ]:
# Utilizando vetor de 1D
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("-"*15)
print(f"Soma: {array1 + 500}")
print("-"*15)
print(f"Substração: {array1 - 500.5}")
print("-"*15)
print(f"Multiplicação: {array1 * 1 + 0.5j}")
print("-"*15)
print(f"Divisão: {array1 / 0.1}")
print("-"*15)
print(f"Modulo: {array1 % 2}")
print("-"*15)
print(f"Parte inteira: {array1 // 2}")

In [ ]:
# Utilizando matrix de 2D
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("-"*15)
print(f"Soma:\n {array1 + 500}")
print("-"*15)
print(f"Substração:\n {array1 - 500.5}")
print("-"*15)
print(f"Multiplicação:\n {array1 * 1 + 0.5j}")
print("-"*15)
print(f"Divisão:\n {array1 / 0.1}")
print("-"*15)
print(f"Modulo:\n {array1 % 2}")
print("-"*15)
print(f"Parte inteira:\n {array1 // 2}")

In [ ]:
# Operações algebraicas entre vetores
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array2 = array1[::-1]
print(f"Array1 = {array1}")
print(f"Array2 = {array2}")
print(f"Soma: {array1 + array2}")
print("-"*15)
print(f"Substração: {array1 - array2}")
print("-"*15)
print(f"Multiplicação: {array1 * array2}")
print("-"*15)
print(f"Divisão: {array1 / array2}")
print("-"*15)
print(f"Modulo: {array1 % array2}")
print("-"*15)
print(f"Parte interia: {array1 // array2}")

In [ ]:
# Operações algebraicas entre matrices
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = array1.T
print(f"Array1 = \n{array1}")
print(f"Array2 = \n{array2}")
print(f"Soma: \n{array1 + array2}")
print("-"*15)
print(f"Substração: \n{array1 - array2}")
print("-"*15)
print(f"Multiplicação: \n{array1 * array2}")
print("-"*15)
print(f"Divisão: \n{array1 / array2}")
print("-"*15)
print(f"Modulo: \n{array1 % array2}")
print("-"*15)
print(f"Parte interia: \n{array1 // array2}")
