# Aula 11. NumPy

NumPy é uma das bibliotecas mais poderosas da linguagem Python. Esta biblioteca trabalha com matrizes e arrays multidimensionais. Possui uma grande coleção de funções para realizar operações matemáticas com alta performance (como vimos na aula de comparação performática).

- Esta biblioteca possui seus próprios tipos de dados os quais são do tipo `numpy.ndarray`;
- Trabalhar com matrizes e vetores usando np.ndarrays é mais eficiente que utilizar objetos do tipo lista;
- Numpy é utilizada amplamente para realizar:
    - Computação quântica;
    - Computação estatística; 
    - Processamento de sinal;
    - Processamento de imagem;
    - Visualização 3D;
    - Computação simbólica;
    - Processamento astronômico;
    - BioInoformatica;
    - Inferência Bayesiana;
    - Análise matemática;
    - Simulação e modelagem (Monte Carlo);
    - Análise de multivariável;
    - E infinidades de outras alternativas.
- Recomendo (fortemente) visitar o site de [Numpy](https://numpy.org/) para conhecer mais sobre esta biblioteca.
---
O objetivo de hoje é apresentar os aspectos **mais básicos** desta biblioteca devido a que conta com grande variedades de funções e aplicações. Vamos nos concentrar em:
- List vs Numpy;
- Indexação e fatiamento Numpy;
- Arrays fila e arrays coluna;
- Eliminando elementos, função delete;
- Adicionando elementos insert e append;
- Operações algebraicas com arrays (+, -, *, /, //, %);
- Cannivete NumPy:
 - arange;
 - linspace;
 - ones, zeros e eye;
 - Shape;
 - Size;
 - dimensão;
 - reshape;
 - asarray;
 - where;
- Carregando dados com Numpy.


## Listas vs Numpy

In [5]:
import numpy as np

In [6]:
l1  = [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]
l1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
# Acessando à primeira fila
l1[0]

[1, 2, 3]

In [8]:
# E para acessar à primeira coluna?
l1[:]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
array1  = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Acessando à primeira fila
array1[0,:]

array([1, 2, 3])

In [13]:
array1[:, 0]

array([1, 4, 7])

In [12]:
# Acessando à primeira coluna
array1[:, -1]

array([3, 6, 9])

## Indexação e fatiamento

Os Arrays se comportam da mesma forma que as listas (até certo ponto), a sua indexação inicia em 0 e vai até o último elemento representado por -1.

In [14]:
array = np.array([0,1,2,3,4,5,6])

In [15]:
print(array) # Imprimindo o array
print(array[:]) # acessando ao todos os elementos
print(array[0]) # acessando ao primer elemento
print(array[1]) # acessando ao segundo elemento
print(array[-1]) # acessando ao ultimo elemeto

[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6]
0
1
6


In [18]:
print(array[1:-1]) # fatiando um array 
print(array[0:3]) # fatiando um array
print(array[1:]) # fatiando um array
print(array[0::2]) # fatiando um array com `step`
# Observemos que o último é excluido

[1 2 3 4 5]
[0 1 2]
[1 2 3 4 5 6]
[0 2 4 6]


Como seria o fatiamento de uma matriz?

$$array =   \left( \begin{matrix} a & b \\ c & d \end{matrix} \right)$$
$$array[:, 0] =   \left( \begin{matrix} a & c  \end{matrix} \right)$$
$$array[0, :] =   \left( \begin{matrix} a & b  \end{matrix} \right)$$
$$array[row, colum])$$

In [19]:
# Como seria o fatiamento com uma matriz?
print("Array original")
print(array1[:]) # Toda a matriz

Array original
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print("Todos os elementos da primeira fila")
print(array1[0, :]) # Todos os elementos da primeira fila
print(array1[0])
print(array1[0][:])

Todos os elementos da primeira fila
[1 2 3]
[1 2 3]
[1 2 3]


In [21]:
print("Todos os elementos da última fila")
print(array1[-1, :]) # Todos os elementos da última fila
print(array1[-1][:]) 
print(array1[-1]) 

Todos os elementos da última fila
[7 8 9]
[7 8 9]
[7 8 9]


In [22]:
print("Todos os elementos da primeira coluna")
print(array1[:, 0]) # Todos os elementos da primeira coluna
print(array1[:][0]) # ?

Todos os elementos da primeira coluna
[1 4 7]
[1 2 3]


In [25]:
array1[:][0]

array([1, 2, 3])

In [26]:
print("Todos os elementos da última coluna")
print(array1[:, -1]) # Todos os elementos da última coluna

Todos os elementos da última coluna
[3 6 9]


In [27]:
print("segundo elemento da segunda coluna")
print(array1[1, 1]) # segundo elemento da segunda coluna

segundo elemento da segunda coluna
5


## Array fila e array coluna

Algumas IDEs podem mostrar os array coluna da mesma forma que um array vetor. Porém esses são objetos diferentes. Além disso, algumas operações matriciais precisam do vetor em configurado como uma fila e não como uma coluna.

In [28]:
array = np.array([1, 2, 3])
array_coluna = np.array([[1], [2], [3]])
array_fila = np.array([[1, 2, 3]])

In [30]:
print(array)
print(array_coluna)
print(array_fila)

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]


In [31]:
print("size")
print(array.size)
print(array_coluna.size)
print(array_fila.size)

size
3
3
3


In [32]:
print("shape")
print(array.shape)
print(array_coluna.shape)
print(array_fila.shape)

shape
(3,)
(3, 1)
(1, 3)


In [33]:
print("Dimensão")
print(array.ndim)
print(array_coluna.ndim)
print(array_fila.ndim)

Dimensão
1
2
2


## Eliminando elementos, função delete

In [34]:
print("Arrey Original")
print(array1)
print("-"*15)
print("Eliminando a primeira fila")
print(np.delete(array1, 0, 0)) # Eliminando a primeira fila
print("-"*15)
print("Eliminando a primeira coluna")
print(np.delete(array1, 0, 1)) # Eliminando a primeira coluna

Arrey Original
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
Eliminando a primeira fila
[[4 5 6]
 [7 8 9]]
---------------
Eliminando a primeira coluna
[[2 3]
 [5 6]
 [8 9]]


## Adicionando elementos append e insert 

### append

In [40]:
print("Array original")
print(np.array(np.array([1, 2, 3])))
print("Adicionando todos os elementos no final do array 1D")
np.append(array, [7,8,9])  # Adicionando todos os elementos no final do array 1D

Array original
[1 2 3]
Adicionando todos os elementos no final do array 1D


array([1, 2, 3, 7, 8, 9])

In [45]:
array

array([1, 2, 3])

In [47]:
print("Array original")
print(np.array([[1, 2, 3]]) )
print("Adicionando os elementos como uma nova fila")
np.append(np.array([[1, 2, 3]]), [[10, 20, 30]], axis=0) # Adicionando os elementos como uma nova fila

Array original
[[1 2 3]]
Adicionando os elementos como uma nova fila


array([[ 1,  2,  3],
       [10, 20, 30]])

In [55]:
print("Array original")
print(np.array([[1, 2, 3]]))
print("Adicionando os elementos como novas colunas")
np.append(np.array([[1, 2, 3]]), [[10, 20, 30]], axis=1) # Adicionando os elementos como novas colunas

Array original
[[1 2 3]]
Adicionando os elementos como novas colunas


array([[ 1,  2,  3, 10, 20, 30]])

In [51]:
np.array([[1, 2, 3]]).shape

(1, 3)

### insert

In [56]:
print("Array original")
print(array1)
print("-"*15)
print("Adicionando uma fila com o mesmo valor")
print(np.insert(array1, 0, 100, 0)) # Adicionando uma fila com o mesmo valor
print("-"*15)
print("Adicionando uma coluna com o mesmo valor")
print(np.insert(array1, 0, 100, 1)) # Adicionando uma coluna com o mesmo valor
print("-"*15)

Array original
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
Adicionando uma fila com o mesmo valor
[[100 100 100]
 [  1   2   3]
 [  4   5   6]
 [  7   8   9]]
---------------
Adicionando uma coluna com o mesmo valor
[[100   1   2   3]
 [100   4   5   6]
 [100   7   8   9]]
---------------


In [57]:
print("Array original")
print(array1)
print("-"*15)
print("Adicionando uma fila com o mesmo valor")
print(np.insert(array1, 0, [100, 200, 300], 0)) # Adicionando uma fila com o mesmo valor
print("-"*15)
print("Adicionando uma coluna com o mesmo valor")
print(np.insert(array1, 0,  [100, 200, 300], 1)) # Adicionando uma coluna com o mesmo valor
print("-"*15)

Array original
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
Adicionando uma fila com o mesmo valor
[[100 200 300]
 [  1   2   3]
 [  4   5   6]
 [  7   8   9]]
---------------
Adicionando uma coluna com o mesmo valor
[[100   1   2   3]
 [200   4   5   6]
 [300   7   8   9]]
---------------


### Modificando um unico elemento

In [58]:
print("Array original")
array1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print(array1)
print("Array modificado")
array1[1, 1] = 500
print(array1)

Array original
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array modificado
[[  1   2   3]
 [  4 500   6]
 [  7   8   9]]


In [62]:

array1 + 1000

array([[1001, 1002, 1003],
       [1004, 1500, 1006],
       [1007, 1008, 1009]])

## Operações algebraicas
Uma das vantagens dos numpy.ndarray é que as operações algebraicas estão definidas entre esse tipo de dados e dados do tipo numérico como float, int e complex. 

Lembrando que estas operações não estão definidas entre objetos do tipo lista

In [63]:
# Utilizando vetor de 1D
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("-"*15)
print(f"Soma: {array1 + 500}")
print("-"*15)
print(f"Substração: {array1 - 500.5}")
print("-"*15)
print(f"Multiplicação: {array1 * 1 + 0.5j}")
print("-"*15)
print(f"Divisão: {array1 / 0.1}")
print("-"*15)
print(f"Modulo: {array1 % 2}")
print("-"*15)
print(f"Parte inteira: {array1 // 2}")

---------------
Soma: [501 502 503 504 505 506 507 508 509]
---------------
Substração: [-499.5 -498.5 -497.5 -496.5 -495.5 -494.5 -493.5 -492.5 -491.5]
---------------
Multiplicação: [1.+0.5j 2.+0.5j 3.+0.5j 4.+0.5j 5.+0.5j 6.+0.5j 7.+0.5j 8.+0.5j 9.+0.5j]
---------------
Divisão: [10. 20. 30. 40. 50. 60. 70. 80. 90.]
---------------
Modulo: [1 0 1 0 1 0 1 0 1]
---------------
Parte inteira: [0 1 1 2 2 3 3 4 4]


In [64]:
# Utilizando matrix de 2D
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("-"*15)
print(f"Soma:\n {array1 + 500}")
print("-"*15)
print(f"Substração:\n {array1 - 500.5}")
print("-"*15)
print(f"Multiplicação:\n {array1 * 1 + 0.5j}")
print("-"*15)
print(f"Divisão:\n {array1 / 0.1}")
print("-"*15)
print(f"Modulo:\n {array1 % 2}")
print("-"*15)
print(f"Parte inteira:\n {array1 // 2}")

---------------
Soma:
 [[501 502 503]
 [504 505 506]
 [507 508 509]]
---------------
Substração:
 [[-499.5 -498.5 -497.5]
 [-496.5 -495.5 -494.5]
 [-493.5 -492.5 -491.5]]
---------------
Multiplicação:
 [[1.+0.5j 2.+0.5j 3.+0.5j]
 [4.+0.5j 5.+0.5j 6.+0.5j]
 [7.+0.5j 8.+0.5j 9.+0.5j]]
---------------
Divisão:
 [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
---------------
Modulo:
 [[1 0 1]
 [0 1 0]
 [1 0 1]]
---------------
Parte inteira:
 [[0 1 1]
 [2 2 3]
 [3 4 4]]


In [67]:
# Operações algebraicas entre vetores
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array2 = array1[::-1]
print(f"Array1 = {array1}")
print(f"Array2 = {array2}")
print(f"Soma: {array1 + array2}")
print("-"*15)
print(f"Substração: {array1 - array2}")
print("-"*15)
print(f"Multiplicação: {array1 * array2}")
print("-"*15)
print(f"Divisão: {array1 / array2}")
print("-"*15)
print(f"Modulo: {array1 % array2}")
print("-"*15)
print(f"Parte interia: {array1 // array2}")

Array1 = [1 2 3 4 5 6 7 8 9]
Array2 = [9 8 7 6 5 4 3 2 1]
Soma: [10 10 10 10 10 10 10 10 10]
---------------
Substração: [-8 -6 -4 -2  0  2  4  6  8]
---------------
Multiplicação: [ 9 16 21 24 25 24 21 16  9]
---------------
Divisão: [0.11111111 0.25       0.42857143 0.66666667 1.         1.5
 2.33333333 4.         9.        ]
---------------
Modulo: [1 2 3 4 0 2 1 0 0]
---------------
Parte interia: [0 0 0 0 1 1 2 4 9]


In [68]:
# Operações algebraicas entre matrices
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = array1.T
print(f"Array1 = \n{array1}")
print(f"Array2 = \n{array2}")
print(f"Soma: \n{array1 + array2}")
print("-"*15)
print(f"Substração: \n{array1 - array2}")
print("-"*15)
print(f"Multiplicação: \n{array1 * array2}")
print("-"*15)
print(f"Divisão: \n{array1 / array2}")
print("-"*15)
print(f"Modulo: \n{array1 % array2}")
print("-"*15)
print(f"Parte interia: \n{array1 // array2}")

Array1 = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array2 = 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Soma: 
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
---------------
Substração: 
[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]
---------------
Multiplicação: 
[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
---------------
Divisão: 
[[1.         0.5        0.42857143]
 [2.         1.         0.75      ]
 [2.33333333 1.33333333 1.        ]]
---------------
Modulo: 
[[0 2 3]
 [0 0 6]
 [1 2 0]]
---------------
Parte interia: 
[[1 0 0]
 [2 1 0]
 [2 1 1]]


## Cannivete Numpy

### Array arange()

Função para criar um array de `n` elementos.

numpy.arange([start, ]stop, [step, ]dtype=None)

In [ ]:
arange = np.arange(0, 5)
print(arange)

In [ ]:
arange = np.arange(start=0, stop=5, step=1)
print(arange)

In [ ]:
arange = np.arange(start=0, stop=5, step=0.5)
print(arange)

In [ ]:
arange =np.arange(start=1, stop=100, step=0.05362)
print(arange)

### linspace()
A funcionalidade é muito parecida com np.arange(), porém, está função garante sempre o mesmo espaçamento entre os pontos e o ultimo ponto é inclusivo.

 numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]

In [ ]:
linspace = np.linspace(start=1, stop=5, num=5)
print(linspace)

In [ ]:
linspace = np.linspace(start=1, stop=100, num=50)
print(linspace)

In [3]:
[linspace[i+1] - linspace[i] for i in range(len(linspace)-1)]

NameError: name 'linspace' is not defined

**Cuidado com os espaçamento ao se utilizar np.arange() e np.linspace()**

### ones, zeros e eye

Numpy possui algumas funções para a criação de array de forma automática preenchidos com alguns valores. Este é o caso das funções `ones`, `zeros` e `aye`, as quais retornar array preenchidas com valores de 1, 0 e array com diagonal de 1.
```python
numpy.ones(shape, dtype=None, order='C')

numpy.zeros(shape, dtype=float, order='C')

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
```

In [ ]:
np.ones(shape=(10,))

In [ ]:
np.ones(shape=(10,1))

In [ ]:
np.ones(shape=(1, 10))

In [ ]:
np.ones(shape=(10,10))

In [ ]:
np.zeros(shape=(10, 10), dtype=float)

In [70]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [69]:
np.eye(10,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.eye(10,10, k=2)

### Shape()

Retorna a ***configuração*** de um array

In [ ]:
ones = np.ones((5,5))
print(ones)
np.shape(ones)

In [ ]:
ones = np.ones((5, 1))
print(ones)
np.shape(ones)

In [ ]:
ones = np.ones((1,5)) 
print(ones)
np.shape(ones)

In [ ]:
ones = np.ones(15) 
print(ones)
np.shape(ones)

Algumas objetos de numpy (e de outras bibliotecas) tem metodos definidos, e o shape é um deles. Isto quer dizer que podemos fazer `np.shape(ones)` ou `ones.shape` e o resultado vai ser o mesmo.

In [ ]:
ones.shape

### reshape()

Esta função reconfigura um array. Deve-se ter cuidado pois nem sempre é possível realizar a configuração, isto vai depender da forma do array original.
```python
numpy.reshape(a, newshape, order='C')
```

In [ ]:
array_original = np.arange(1, 17)
print(array_original)

In [ ]:
print("Modificando o array para (1, 16)")
print(array_original.reshape(1,16))

In [ ]:
print("Modificando o array para (16, 1)")
print(array_original.reshape(16,1))

In [ ]:
print("Modificando o array para (4, 4)")
print(array_original.reshape(4,4))

In [ ]:
print("Modificando o array para (2, 8)")
print(array_original.reshape(2,8))

In [ ]:
print("Modificando o array para (8, 2)")
print(array_original.reshape(8,2))

In [ ]:
np.reshape(array_original, (8,2))

### size()

Retorna o número de elementos contidos num np.array

In [ ]:
array_original.size

### Dimension ndim()

Retorna o número de dimensões que um array possui.

In [ ]:
print((array_original.ndim))
print(np.ones((10,10)).ndim)
print(array_original.reshape(2,4,2))
print(array_original.reshape(2,4,2).ndim)

### where()

In [ ]:
array_teste = np.random.randint(low=1, high=20, size=20)
print(array_teste)

print(np.where(array_teste<10, array_teste, 0))

In [ ]:
# Usando como filtro e aplicando no array
np.where(array_teste<10, array_teste/10, array_teste)

In [ ]:
# Usando como filtro e aplicando no array
np.where(array_teste<10, array_teste, array_teste/10)

In [ ]:
# usando multiplas comparações
np.where((array_teste>5) & (array_teste<15), array_teste, 0)

In [ ]:
# USando multiplas comparações
np.where((array_teste>5) & (array_teste<15) | (array_teste == 18), array_teste, 0)
# OBS. 

## Salvando e carregando dados

Numpy possui diversas formas de salvar arquivos, dentre elas temos `.csv`, `.txt`, `.npy` e `.npz`, porém vamos só ver o funcionamento com arquivos `.csv`.

In [ ]:
# salvando um arquivo no formato .csv
dados = np.random.rand(1000,1000)
np.savetxt("dados.csv",dados)

In [ ]:
# Carregando o arquivo
import numpy as np
np.loadtxt("dados.csv")
"""
OBSERVAÇÃO
O arquivo que vai ser carregado DEVE estar no mesmo diretório que o arquivo .py (ou .ipynb).
CASO CONTRARIO se deve indicar o endereço do diretório onde temos o arquivo armazenado.
"""

In [ ]:
# Carregando um arquivo ubicado num diretorio diferente
import numpy as np
np.loadtxt("/home/fernan/Área de Trabalho/dados_2.csv")
"""
Observação. O código anterior pode não funcionar só funciona para sistemas basados em POSIX
(UNIX e MAC), para windows não funciona.
"""

In [4]:
import os
os.getcwd()

'/home/fernan/MEGA/1 Vida Academica/Doutorado FEQ/Curso Python LNBR/Curso_Python_Basico_LNBR/Aula 11 Numpy'